version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: flask_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: uts_flask
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    networks:
      - flasknet

  web:
    build: .
    container_name: flask_web_app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass123
      MYSQL_DB: uts_flask
      MYSQL_PORT: 3306
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flasknet

volumes:
  db_data:

networks:
  flasknet:
    driver: bridge
